version: "3"
networks:
  expense:
volumes:
    shared-data: # docker volume create devops
services:
  nginx:
    image: nginx:latest
    container_name: nginx-container
    ports:
     - 8080:80
    volumes:
      - shared-data:/usr/share/nginx/html
    working_dir: /usr/share/nginx/html
  nodejs:
    image: node:16
    container_name: nodejs-container
    volumes:
      - shared-data:/app/shared # Attach the shared volume
    working_dir: /app/shared
    command: sh -c "echo 'Hello All i am from Node.js' > /usr/src/app/index.html && sleep 5;"

# volumes:
#   shared-data:
#     driver: local