apiVersion: apps/v1
kind: Deployment
metadata:
   name: mysql
   namespace: expense-project
   labels:
     name: mysql
     tier: db
     project: expense
spec:
  replicas: 1
  selector:
     matchLabels:
        name: mysql
        tier: db
        project: expense
  template:
     metadata:
       name: expense-pod-mysql
       labels:
          name: mysql
          tier: db
          project: expense
     spec:
       containers:
          - name: mysql
            image: joindevops/mysql:v1

---
apiVersion: v1
kind: Service
metadata:
  name: mysql-service
  namespace: expense-project
  labels: 
    name: mysql
    tier: db
    project: expense
spec:
  selector:
    name: mysql
    tier: db
    project: expense
  ports:
   - name: mysql-port
     protocol: TCP
     port: 3306
     targetPort: 3306


  
      

