apiVersion: v1
kind: Pod
metadata:
  name: pod-annotation
  annotations:
    buildURL: "https://stackoverflow.com/questions/65756827/eksctl-create-cluster-stuck-waiting-for-cloudformation-stack"
spec:
  containers:
  - name: nginx
    image: nginx
