apiVersion: v1
kind: Pod
metadata:
  name: pod-configure
  labels:
    name: podproject
    course: podcourse
    duration: podduration2hurs
  annotations:
    imageURL: "https://github.com/ashwanidevopscloud/practice-1"
spec:
  containers:
    - name: nginx
      image: nginx
      envFrom:
        - configMapRef:
            name: nginx-configure
      resources:
        requests:
          cpu: 40m
          memory: 60Mi
        limits:
          cpu: 80m
          memory: 100Mi
