apiVersion: v1
kind: Pod
metadata:
  labels:
    name: ashwanidevopscloud
    age: 25
    course: softwareeeee
  annotations:
    imageURL: "https://chatgpt.com/c/6781a261-2328-8009-8119-032af47c8fc2"
    courses: "#fT^%$d*&^g()_)(098888888888(((((000000))))))"
spec:
 containers:
   - name: nginx
     image: nginx
     envFrom:
       secreteMapRef:
         - name: secret-configure
     resources:
       requests:
         cpu: 80m
         memory: 69Mi
       limits:
         cpu: 130m
         memory: 120Mi