apiVersion: v1
kind: Pod
metadata:
  name: pod-secrete
  labels:
    name: ashwanidevopscloud
    age: "25"
    course: softwareeeee
  annotations:
    imageURL: "https://chatgpt.com/c/6781a261-2328-8009-8119-032af47c8fc2"
spec:
 containers:
   - name: nginx
     image: nginx
     envFrom:
       - secretRef:
            name: secret-configure
     resources:
        requests:
          cpu: 80m
          memory: 69Mi
        limits:
          cpu: 130m
          memory: 120Mi