apiVersion: v1
kind: Service
metadata:
   name: service-project
spec:
  selector:
    name: ashwanidevopscloud
    age: "25"
    course: softwareeeee
  ports:
    - name: nginx-svc-port
      protocol: TCP
      port: 80
      targetPort: 80