apiVersion: v1
kind: Service
metadata:
  name: node-port
spec:
  type: LoadBalancer
  selector:
    name: podproject
    course: podcourse
    duration: podduration2hurs
  ports:
    - name: nginx-svc-nodeport
      protocol: TCP
      port: 80
      targetPort: 80

  