apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: nginx-replicaset
  labels:
    name: nginx
    course: devops
spec:
  replicas: 3
  selector:
    matchLabels:
      name: nginx
      course: devops
  template:
    metadata:
       name: replicapod
       labels: 
         name: nginx
         course: devops
    spec:
      containers:
        - name: nginx
          image: nginx

---
apiVersion: v1
kind: Service
metadata: 
   name: nginx-service-replicas
   labels:
     name: nginx
     course: devops
spec:
  selector:
     name: nginx
     course: devops
  ports:
   - name: nginx-port-replicas
     protocol: TCP
     port: 80
     targetPort: 80
