apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: nginx-replicaSet
  labels:
    name: nginx
    course: devops
spec:
  replicas: 3
  selector:
    matchLabels:
      name: nginx
      course: devops
  template:
    metadata:
       name: replicapod
       labels: 
         name: nginx
         course: devops
    spec:
      containers:
        - name: nginx
          image: nginx
     
      