apiVersion: v1
kind: Pod
metadata:
  name: limits
  labels:
    project: 3-tier
    environment: dev
    module: backend
  annotation:
    imageURL: "https://github.com/eksctl-io/eksctl/blob/main/examples/01-simple-cluster.yaml"
spec:
  containers:
  - name: nginx
    image: nginx
    env:
     - name: author
       value: shiva
     - name: project
       value: frontend
      - name: course
        value: 120hurs
    resources:
      requests:
        cpu: 100m
        memory: 68mi
      limits:
        cpu: 120m
        memory: 100mi

  - name: almalinux
    image: almalinux:9
    command: ["sleep", "1000"]

