apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment  # Name of your deployment & these are deployemnt labels
  labels:
    app: nginx
spec:
  replicas: 3            # Number of Nginx pods to run
  selector:
    matchLabels:
      app: nginx        # Label selector to match pods
  template:             # Template for creating pods
    metadata:
      labels:
        app: nginx      # Labels assigned to pods
    spec:
      containers:
      - name: nginx      # Name of the container
        image: nginx:latest 

---
apiVersion: v1
kind: Service
metadata:
  name: nginx-service 
  labels:
    app: nginx    
spec:
  selector:
    app: nginx        # Select pods with the label "app: nginx"
  ports:
  - name: nginx-svc-port
    protocol: TCP
    port: 8080       # Port exposed externally
    targetPort: 80   # Port the container is listening on
    nodePort: 30001
  type: NodePort