apiVersion: v1
kind: Pod
metadata:
  name: app-pod
spec:
  containers:
  - name: app-container
    image: busybox
    command: ["sh", "-c", "echo $name; echo $project; echo $message; && sleep 10"] 
    envFrom:  # Inject environment variables from ConfigMap and Secret
    - configMapRef:
        name: app-config
    - secretRef:
        name: app-secret
