apiVersion: v1
kind: Pod
metadata:
  name: app-pod
spec:
  containers:
  - name: app-container
    image: busybox
    envFrom: 
    - configMapRef:
        name: app-config
    - secretRef:
        name: app-secret
