version: "3"
networks:
  expense:
volumes:
  ex-data2: # docker volume create devops
services:
  mysql:
    image: mysql:a1
    container_name: mysql # --name mysql
    volumes:
      - ex-data2:/var/lib/mysql # -v mysql:/var/lib/mysql
  backend:
    image: backend:a1
    container_name: backend
    command: sh -c "sleep 5 && node /app/index.js"
    depends_on:
      - mysql
  frontend:
    image: frontend:a1
    container_name: frontend
    depends_on:
      - backend
    ports:
     - 80:80



