version:"3"
networks:
  expense:
volumes:
  devops: # docker volume create devops
services:
  mysql:
    image: mysql:a1
    container_name: mysql # --name mysql
    volume:
      - devops: /var/lib/mysql # -v mysql:/var/lib/mysql
  backend:
    image: backend:a1
    container_name: backend
    depends_on:
      - mysql
  frontend:
    image: frontend:a1
    container_name: frontend
    depends_on:
      - backend
    ports:
     - 80:80



