apiVersion: v1
kind: PersistentVolume
metadata:
  name: expense-efs-static
spec:
  capacity:
    storage: 5Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  storageClassName: ""
  persistentVolumeReclaimPolicy: Retain
  csi:
    driver: efs.csi.aws.com
    volumeHandle: fs-06450a748f6dae33b
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: expense-efs-static-claim
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: ""
  volumeName: expense-efs-static
  resources:
    requests:
      storage: 5Gi
---
apiVersion: v1
kind: Pod
metadata:
  name: expense-efs-static-pod
  labels:
    project: expense
    module: static-efs
spec:
  containers:
  - name: nginx
    image: nginx
    volumeMounts:
    - name: expense-efs-static
      mountPath: /usr/share/nginx/html
  volumes:
  - name: expense-efs-static
    persistentVolumeClaim:
      claimName: expense-efs-static-claim
---
apiVersion: v1
kind: Service
metadata:
  name: efs-static-service
spec:
  selector:
    project: expense
    module: static-efs
  type: LoadBalancer
  ports:
    - name: node-port-svc
      protocol: TCP
      port: 80
      targetPort: 80 
      nodePort: 30003
